nasa/cumulus-api

content/collections.md
content/granules.md
content/logs.md
content/pdrs.md
content/providers.md
content/stats.md

Went through each API call and updated the responses and URLs to be valid. 
Not sure what I would need to do to publish these doc changes, so please let me know after they are reviewed.

CUMULUS-100 API doc updates

---

content/granules.md

Documents `applyWorkflow` action added to the `granules` endpoint for CUMULUS-681

CUMULUS-681 Ingest In Place

---

README.md
content/execution-status.md
content/executions.md
content/logs.md
template/src/custom/content.js

Add execution logs documentation

Cumulus-720 Update cumulus-api documentation for Dashboard Granule Tracking

---

content/workflows.md
template/src/custom/content.js

Adding Api docs for workflows
Docs for Providers and Collections already exist.

Cumulus-648 Adding Api docs for workflows

---

content/instance-meta.md
template/src/custom/content.js

adds documentation for api endpoint instance metadata. 
https://bugs.earthdata.nasa.gov/browse/CUMULUS-775

Adds instance metadata endpoint to api docs.

---

CONTRIBUTING.md
api-client-py/setup.py
bin/docs
content/collections.md
content/intro.md
content/providers.md
content/rules.md
package.json

CUMULUS-1078 -- Update docs to describe new functionality for running rules from the API
CUMULUS-1080 -- Update API Docs with schemas to show possible values of fields.
* Added note and example request about `rerun` of onetime rules to update-rule section of apidoc.
* Replaced references to `cumulus-nasa` with `nasa`.
* Updated collections API doc with fields reference
* Updated providers API doc with fields reference
* Updated rules API doc with fields reference

CUMULUS-1078 & CUMULUS-1080 updates

---

content/executions.md

Update documentation for execution endpoint with execution retention keys

Add execution retention fields to API execution documentation

---

content/intro.md

See <https://www.elastic.co/guide/en/kibana/current/lucene-query.html>

Fix syntax error in Lucene query syntax

---

content/collections.md

Adds documentation for the collections w/ active granules endpoint

[CUMULUS-1787] Add active collection endpoint documentation

---

content/collections.md

Updates docs for new /collection functionality.

Add information on getMMT and /collection endpoints

---

content/reconciliation-reports.md

Adds status param to reports. Also adds a note about Granule Inventory reports. Slight tweaks to make rendering better.

CUMULUS-2170 Add status param to reports

---

content/elasticsearch.md

* Update reindex and change index operations to reflect the changes in CUMULUS-2344
* Add parameters table for reindex and change index

[CUMULUS-2344] Update Reindex docs

---

content/granules.md

Corresponds with https://github.com/nasa/cumulus/pull/2138

update bulk granules API docs

---

content/elasticsearch.md

Just notes that the reindex needs to have a new index or it will fail.

update reindex docs.

---

content/reconciliation-reports.md

Update the example return value to represent the change for reconciliation reports to run as asyncOperations.

Updates return value of reconciliation report

---

content/replays-sqs-messages.md

https://bugs.earthdata.nasa.gov/browse/CUMULUS-2373
https://github.com/nasa/cumulus/pull/2373

[CUMULUS-2373] Add documentation for replays/sqs endpoint

---

content/providers.md

Add `allowedRedirects` and `certificateUri` fields to create provider docs

[CUMULUS-2747] Update providers documentation

---

content/dead-letter-archive.md
content/orca.md
template/src/custom/content.js

Adds documentation for DLQ recovery endpoint (CUMULUS-2869)

Add endpoint documentation for recoverCumulusMessages

---

content/executions.md
content/orca.md

https://github.com/nasa/cumulus/pull/3123

CUMULUS-2915:Update /executions/status/executionArn endpoint doc

---

release.md
website/index.html

PR with a few PR suggestions for #330

re-wrap .md files for length considerations

---

content/granules.md

Add documentation of the endpoint added in https://github.com/nasa/cumulus/pull/3912

CUMULUS-3992: Add documentation for bulkChangeCollection endpoint

---

content/granules.md

Fixes/updates for 3992 related to headers/formatting to get the rendering right on the docs page.

Fix formatting/headers/etc

---

content/intro.md

Update API doc to reflect changes in https://github.com/nasa/cumulus/pull/3952/files

---

content/executions.md

Remove errant ES reference in execution deletion endpoint

Update docs to remove ES reference

---

content/granules.md

Added CUMULUS-4101 to remove Internal Reconcilation Report document

CUMULUS-4068:Update documentation to include producerGranuleId in granule
